---
title: "COVID 2"
author: "Cesar Poggi"
date: '2022-09-06'
output: html_document
---

```{r}
library(rio)
OWIDtablas = import("owid-covid-tablas para Casos y Muertes V2.csv")
```

```{r}
library(dplyr)
OWIDtablas$date <- as.Date(OWIDtablas$date, '%d/%m/%Y')
OWIDtablas <- OWIDtablas %>%
  filter(date == '2022/09/15')

OWIDtablas <- OWIDtablas %>%
  filter(continent == 'Africa' | continent == 'Asia' | continent == 'North America' | continent == 'Europe' | continent == 'Oceania' | continent == 'South America' )
```

```{r}
OWIDtablas = OWIDtablas[c(3:5,8,11,14,49)]
#OWIDtablas = OWIDtablas[-c(3,4)]
```

#SIMPLIFICAR
```{r}
OWIDtablasMUERTES = OWIDtablas[c(1,4,6,7)]
OWIDtablasCASOS = OWIDtablas[c(1,3,5,7)]
OWIDtablasBOTH = OWIDtablas[c(1,3,4,5,6,7)]
```

```{r}
OWIDtablasMUERTES$Ranking <- rank(desc(OWIDtablasMUERTES$total_deaths_per_million))
OWIDtablasCASOS$Ranking <- rank(desc(OWIDtablasCASOS$total_cases_per_million))
OWIDtablasMUERTES= arrange(OWIDtablasMUERTES, Ranking)
OWIDtablasCASOS= arrange(OWIDtablasCASOS, Ranking)
```

```{r}
library(magrittr)
OWIDtablasCASOS%>%
  rmarkdown::paged_table()
```


CASOS VERSION PLOTLY
```{r}
library(ggplot2)
library(plotly)

OWIDtablasCASOS <- OWIDtablasCASOS %>% 
  mutate(highlgt = ifelse(Ranking == 54 | Ranking == 66 | Ranking == 72 | Ranking == 73 | Ranking == 87 | Ranking == 104 | Ranking == 111 | Ranking == 114 | Ranking == 117 | Ranking == 134 | Ranking == 136 | Ranking == 139 | Ranking == 140 | Ranking == 142 | Ranking == 147 | Ranking == 158 | Ranking == 198, "rgb(255, 255, 97)",
                          ifelse(Ranking == 103, "rgb(252, 113, 104)", "white")))

fig <- plot_ly(
  type = 'table',
  columnwidth = c(80,60,60,60,30),
  columnorder = c(0,1,2,3,4),
  header = list(
    values = c("País","Casos Totales", "Casos por Millón", "Población","Ranking"),
    align = c("left", "center"),
    line = list(width = 1, color = 'black'),
    fill = list(color = c("grey", "grey")),
    font = list(family = "Arial", size = 14, color = "white")
  ),
  cells = list(
    values = rbind(OWIDtablasCASOS$location, OWIDtablasCASOS$total_cases, OWIDtablasCASOS$total_cases_per_million, OWIDtablasCASOS$population, OWIDtablasCASOS$Ranking),
    align = c("left", "center"),
    line = list(color = "black", width = 1),
    font = list(family = "Arial", size = 12, color = c("black")),
                fill = list(color = list(OWIDtablasCASOS$highlgt)))
  ) 

fig
```

MUERTES VERSION PAGED TABLE
```{r}
colnames(OWIDtablasMUERTES)[c(1,2,3,4,5)]<-c("País", "Muertes Totales", "Muertes por Millón", "Población", "Ranking")

library(magrittr)
OWIDtablasMUERTES%>%
  rmarkdown::paged_table()

```

BOTH VERSION PLOTLY
```{r}
library(ggplot2)
library(plotly)

fig2 <- plot_ly(
  type = 'table',
  columnwidth = c(80,60,60,60,60,60),
  columnorder = c(1,2,3,4,5,6),
  header = list(
    values = c("País","Casos Totales", "Muertes Totales", "Casos por Millón", "Muertes por Millón", "Población"),
    align = c("left", "center", "center", "center","center","center"),
    line = list(width = 1, color = 'black'),
    fill = list(color = c("grey", "grey")),
    font = list(family = "Arial", size = 14, color = "white")
  ),
  cells = list(
    values = rbind(OWIDtablasBOTH$location, OWIDtablasBOTH$total_cases, OWIDtablasBOTH$total_deaths, OWIDtablasBOTH$total_cases_per_million, OWIDtablasBOTH$total_deaths_per_million, OWIDtablasBOTH$population),
    align = c("left", "center","center","center","center","center"),
    line = list(color = "black", width = 1),
    font = list(family = "Arial", size = 12, color = c("black"))
  ))

fig2
```

BOTH VERSION PAGED TABLE
```{r}
colnames(OWIDtablasBOTH)[c(1,2,3,4,5,6)]<-c("País", "Casos Totales", "Muertes Totales", "Casos por Millón", "Muertes por Millón", "Población")

library(magrittr)
OWIDtablasBOTH%>%
  rmarkdown::paged_table()
```

